### ISSUE TITLE
ab ab

### ISSUE THREAD

**Issue by CrawLeyYou** [MrHakan/Agalar-Hack#1]
ab 2b2t'de çalışan fly hilesi istiyorum 500km/h

**Comment by Luxotick** [comment]
document.addEventListener('DOMContentLoaded', function() {
  const existingDiv = document.querySelector('div');
  const divContents = JSON.parse(localStorage.getItem('divContents'));
  if (divContents) {
    divContents.forEach(function(content) {
      const divWrapper = document.createElement('div');
      divWrapper.classList.add('div-wrapper');
      const paragraph = document.createElement('p');
      paragraph.textContent = content;
      divWrapper.appendChild(paragraph);
      existingDiv.appendChild(divWrapper);
    });
  }
});

**Comment by Luxotick** [comment]
sry wrong text
